language: ruby
rvm:
  - "3.0.0"
before_script:
  - psql -c 'create database joss_test' -U postgres
  - bundle install
  - bundle exec rails db:schema:load
before_install:
  - gem update bundler
  - nvm install node
script: bundle exec rails spec
addons:
  postgresql: "9.6"
services:
  - elasticsearch
