language: ruby
rvm:
  - "2.6.3"
before_script:
  - psql -c 'create database joss_test' -U postgres
  - bundle install
  - bundle exec rake db:schema:load
before_install:
  - gem update --system
  - gem install bundler:2.0.1
script: bundle exec rake
addons:
  postgresql: "9.6"
services:
  - elasticsearch
